server:
  port: 8081

santander:
  client:
    endereco:
      url: http://localhost:8082/enderecos
    cpf:
      url: http://localhost:8082/cpfs

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: santander
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/santander
    username: root
    password: example
    driver-class-name: com.mysql.cj.jdbc.Driver